services:
  frontend:
    build:
      context: ./homepage_frontend_container
      dockerfile: Dockerfile
    container_name: homepage_frontend_container
    image: homepage_frontend_container
    volumes:
      - ./homepage_frontend_container:/app
    ports:
      - "3000:3000" # 本番用
      - "5173:5173" # 開発用
    tty: true   # コンテナをデバッグ用に起動状態に保つ場合は設定
    # command: ["/bin/sh", "-c", "cd /app/homepage_react-router && npm run dev"]

